import type { Cemetery } from '@/types.ts'

export default [
  {
    id: 'gdansk-lostowicki',
    name: 'Cmentarz Łostowicki',
    city: 'Gdańsk',
    founded: '1906/1979',
    closed: null,
    address: 'Gdańsk, ul. Łostowicka 35, 80-001 Gdańsk',
    latitude: 54.341202777778,
    longitude: 18.597042,
    phone: '58 302 02 07',
    email: 'gzz@gdansk.gda.pl',
    openingHours: 'Czynny całą dobę',
    notes: `
    Początki tej największej gdańskiej nekropolii sięgają założonego około 1906 roku cmentarza przy siedleckim kościele św. Franciszka z Asyżu (zbudowanym w latach 1904–1906). Najstarsza część – cmentarz św. Franciszka (Franziskus Friedhof), wraz z zachowanymi historycznymi nagrobkami, znajduje się od strony ul. Kartuskiej, naprzeciw dworu Krzyżowniki.
    \n\n
    Przed II wojną światową ulica, przy której znajdował się cmentarz, nosiła nazwę (niem.) Wonneberger Weg. Po II wojnie światowej zmieniono nazwę na ulicę Łostowicką, od której zaczęto nazywać cmentarz. Cmentarz został przekazany do użytku w 1979 roku.
    \n\n
    11 listopada 1998 roku odsłonięto pomnik „Pietà Sybiraków”, zwany też „pomnikiem Matki Polki” lub „Pomnikiem Ofiar Golgoty Wschodu” (zob. Światowy Dzień Sybiraka). Usytuowany jest przy głównej alei cmentarza, w „Kwaterze Sybiraków”. Pomnik powstał dzięki staraniom Związku Sybiraków i Rodziny Katyńskiej.
    \n\n
    W 2008 roku na cmentarzu powstała pierwsza na Pomorzu zbiorowa mogiła przeznaczona na pochówki dzieci nienarodzonych.
    \n\n
    W latach 2021–2022 powiększono cmentarz o 1,8 ha od strony al. Armii Krajowej i ul. Cedrowej, co przyniosło ponad 2100 dodatkowych miejsc pochówku (8 kwater). We wrześniu 2021 w 68. kwaterze cmentarza, przy głównej alei za pomnikiem Ponarskim, odsłonięto ok. 2,5-metrowy głaz z napisem "Pamięci Polonii Gdańskiej, Kaszubów i Pomorzan / Walczących o Niepodległą oraz ginących w miejscach kaźni i na polach bitew / W latach 1939–1945 / Mieszkanki i Mieszkańcy Gdańska i Pomorza / 2020".
    `,
  },
  {
    id: 'gdansk-srebrzysko',
    name: 'Cmentarz Srebrzysko',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-oliwski',
    name: 'Cmentarz Oliwski',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-garnizonowy',
    name: 'Cmentarz Garnizonowy',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-komunalny-sw-franciszka',
    name: 'Cmentarz Komunalny św. Franciszka',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-sw-ignacego-loyoli',
    name: 'Cmentarz przy kościele p.w. Św. Ignacego Loyoli',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-komunalny-sw-jadwigi',
    name: 'Cmentarz Komunalny św. Jadwigi',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-salvator-nowy',
    name: 'Cmentarz Komunalny Salvator Nowy',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-sobieszewo',
    name: 'Cmentarz Komunalny Sobieszewo',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-sw-walentego',
    name: 'Cmentarz Parafialny przy parafii p.w. Św. Walentego',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-sw-wojciecha',
    name: 'Cmentarz Parafialny przy parafii p.w. Św. Wojciecha',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-krakowiec-najswietszego-imienia-maryi',
    name: 'Cmentarz Parafialny na Krakowcu (NMP)',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-kielpino-sw-jana-chrzciciela',
    name: 'Cmentarz Parafialny w Kiełpinie (Św. Jana Chrzciciela)',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-kokoszki-sw-brata-alberta',
    name: 'Cmentarz Parafialny w Kokoszkach (Św. Brata Alberta)',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-bretowo-mb-nieustajacej-pomocy',
    name: 'Cmentarz w Brętowie (MB Nieustającej Pomocy)',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-ujescisko-wonneberg',
    name: 'Cmentarz Ujeścisko (Wonneberg Friedhof)',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-mauzoleum-zolnierzy-radzieckich',
    name: 'Cmentarz Mauzoleum Żołnierzy Radzieckich',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-ofiar-hitleryzmu',
    name: 'Cmentarz Ofiar Hitleryzmu',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-wojskowy-francuski',
    name: 'Cmentarz Wojskowy Francuski',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdansk-zydowski',
    name: 'Cmentarz Żydowski',
    city: 'Gdańsk',
    founded: null,
    closed: null,
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },

  {
    id: 'gdynia-witominski',
    name: 'Cmentarz Witomiński',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-maly-kack',
    name: 'Cmentarz Komunalny Mały Kack',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-sw-michala-archaniola',
    name: 'Cmentarz przy parafii p.w. Św. Michała Archanioła',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-sw-mikolaja',
    name: 'Cmentarz przy parafii p.w. Św. Mikołaja',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-sw-andrzeja-boboli',
    name: 'Cmentarz Parafialny przy parafii p.w. Św. Andrzeja Boboli',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-sw-wawrzynca',
    name: 'Cmentarz Parafialny przy kościele p.w. Św. Wawrzyńca',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-matki-boskiej-bolesnej',
    name: 'Cmentarz Parafialny przy parafii p.w. Matki Boskiej Bolesnej',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-chrystusa-dobrego-pasterza',
    name: 'Cmentarz Parafialny przy parafii p.w. Chrystusa Dobrego Pasterza',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-marynarki-wojennej',
    name: 'Cmentarz Parafialny Marynarki Wojennej',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'gdynia-obroncow-wybrzeza',
    name: 'Cmentarz Obrońców Wybrzeża',
    city: 'Gdynia',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },

  {
    id: 'sopot-komunalny',
    name: 'Cmentarz Komunalny w Sopocie',
    city: 'Sopot',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'sopot-katolicki',
    name: 'Cmentarz Katolicki',
    city: 'Sopot',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'sopot-najswietszego-serca-jezusa',
    name: 'Cmentarz Parafialny przy parafii p.w. Najświętszego Serca Pana Jezusa',
    city: 'Sopot',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'sopot-zolnierzy-radzieckich',
    name: 'Cmentarz Żołnierzy Radzieckich',
    city: 'Sopot',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
  {
    id: 'sopot-zydowski',
    name: 'Cmentarz Żydowski',
    city: 'Sopot',
    address: null,
    latitude: null,
    longitude: null,
    phone: null,
    email: null,
    openingHours: null,
    notes: null,
  },
] as Cemetery[]
